### ISSUE TITLE
Running storybook-example with jest 28.1.1

### ISSUE THREAD

**Issue by mr-t-Durden** [Visual-Regression-Tracker/examples-js#64]
I'm currently unable to run the storybook-example with the latest version of jest (28.1.1). This is required for the design system we are considering for using the VRT.

I'm able to run the example with the following dependencies:
```
"dependencies": {
    "@visual-regression-tracker/agent-playwright": "^4.6.1",
    "jest": "^26.6.3",
    "playwright": "^1.22.2"
  },
```
(updating the playwright-version was necessary for mac12.3 support)

When updating the dependencies to:
```
"dependencies": {
    "@visual-regression-tracker/agent-playwright": "^4.6.1",
    "jest": "^28.1.1",
    "playwright": "^1.22.2"
  },
```
i get the following error:
```
FAIL  src/storybook.spec.js
  ● Test suite failed to run

    ReferenceError: jasmine is not defined

      2 |
      3 | if (process.argv.includes("--bail")) {
    > 4 |   const jasmineEnv = jasmine.getEnv();
        |                      ^
      5 |   jasmineEnv.addReporter(failFast.init());
      6 | }
      7 |

      at Object.jasmine (setup-after-env.js:4:22)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
```

Any help would be greatly appreciated.

**Comment by mr-t-Durden** [comment]
simple jest migration solved the issue...
